version: "3.9"

services:
  spring-boot:
    build: .
    restart: on-failure:2
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo/test2
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: test2
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017

networks:
  multiple-db:

